<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-12-10">

<title>ECON 340 - Final Exam | Byeong-Hak Choe</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="assets/css/font.css">
<meta property="og:title" content="ECON 340 - Final Exam | Byeong-Hak Choe">
<meta property="og:description" content="SUNY Geneseo, Fall 2025">
<meta property="og:image" content="/assets/img/posts.png">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./img/geneseo-logo-squared.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">💡 What I Do</span></a>
  </li>  
  <li class="dropdown-header">
 <span class="menu-text"> </span></li>
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">ECON 340 - Final Exam</li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🏠 Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📓 Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://mylearning.suny.edu/d2l/home/2152120" class="sidebar-item-text sidebar-link" target="&quot;_blank&quot;">
 <span class="menu-text">🅱 Brightspace</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./listing-econ-340-lec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🚀 Lecture</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./listing-econ-340-cw.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📝 Classwork</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./listing-econ-340-hw.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📚 Homework</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./listing-econ-340-rw-feedback.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">💡 Research Feedback</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">✍️️ Project</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-rw/econ-340-team-project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📄 Guideline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-rw/econ-340-project-kickoff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🧾 Research Kick-off</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">🗓️ Weeks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 01</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 02</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 03</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 04</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 05</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 06</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 07</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 08</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 09</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 10</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 11</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 12</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 13</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 14</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./econ-wk/wk-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Weeks 15-16</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#section-1.-multiple-choice" id="toc-section-1.-multiple-choice" class="nav-link active" data-scroll-target="#section-1.-multiple-choice">Section 1. Multiple Choice</a>
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a></li>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6">Question 6</a></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">Question 7</a></li>
  <li><a href="#question-8" id="toc-question-8" class="nav-link" data-scroll-target="#question-8">Question 8</a></li>
  <li><a href="#question-9" id="toc-question-9" class="nav-link" data-scroll-target="#question-9">Question 9</a></li>
  </ul></li>
  <li><a href="#section-2.-filling-in-the-blanks" id="toc-section-2.-filling-in-the-blanks" class="nav-link" data-scroll-target="#section-2.-filling-in-the-blanks">Section 2. Filling-in-the-Blanks</a>
  <ul>
  <li><a href="#question-10" id="toc-question-10" class="nav-link" data-scroll-target="#question-10">Question 10</a></li>
  <li><a href="#question-11" id="toc-question-11" class="nav-link" data-scroll-target="#question-11">Question 11</a></li>
  <li><a href="#question-12" id="toc-question-12" class="nav-link" data-scroll-target="#question-12">Question 12</a></li>
  <li><a href="#question-13" id="toc-question-13" class="nav-link" data-scroll-target="#question-13">Question 13</a></li>
  <li><a href="#question-14" id="toc-question-14" class="nav-link" data-scroll-target="#question-14">Question 14</a></li>
  </ul></li>
  <li><a href="#section-3.-short-answers" id="toc-section-3.-short-answers" class="nav-link" data-scroll-target="#section-3.-short-answers">Section 3. Short Answers</a>
  <ul>
  <li><a href="#question-15-risk-uncertainty-and-the-precautionary-principle" id="toc-question-15-risk-uncertainty-and-the-precautionary-principle" class="nav-link" data-scroll-target="#question-15-risk-uncertainty-and-the-precautionary-principle">Question 15 — Risk, Uncertainty, and the Precautionary Principle</a>
  <ul>
  <li><a href="#part-a" id="toc-part-a" class="nav-link" data-scroll-target="#part-a">Part A</a></li>
  <li><a href="#part-b" id="toc-part-b" class="nav-link" data-scroll-target="#part-b">Part B</a></li>
  <li><a href="#part-c" id="toc-part-c" class="nav-link" data-scroll-target="#part-c">Part C</a></li>
  <li><a href="#part-d" id="toc-part-d" class="nav-link" data-scroll-target="#part-d">Part D</a></li>
  <li><a href="#part-e" id="toc-part-e" class="nav-link" data-scroll-target="#part-e">Part E</a></li>
  </ul></li>
  <li><a href="#question-16-social-discount-rate-sdr-and-social-cost-of-carbon-scc" id="toc-question-16-social-discount-rate-sdr-and-social-cost-of-carbon-scc" class="nav-link" data-scroll-target="#question-16-social-discount-rate-sdr-and-social-cost-of-carbon-scc">Question 16 — Social Discount Rate (SDR) and Social Cost of Carbon (SCC)</a>
  <ul>
  <li><a href="#part-a-1" id="toc-part-a-1" class="nav-link" data-scroll-target="#part-a-1">Part A</a></li>
  <li><a href="#part-b-1" id="toc-part-b-1" class="nav-link" data-scroll-target="#part-b-1">Part B</a></li>
  <li><a href="#part-c-1" id="toc-part-c-1" class="nav-link" data-scroll-target="#part-c-1">Part C</a></li>
  <li><a href="#part-d-1" id="toc-part-d-1" class="nav-link" data-scroll-target="#part-d-1">Part D</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#section-5.-analytical-modeling" id="toc-section-5.-analytical-modeling" class="nav-link" data-scroll-target="#section-5.-analytical-modeling">Section 5. Analytical Modeling</a>
  <ul>
  <li><a href="#question-17.-valuing-climate-adaptation-reducing-heatwave-deaths" id="toc-question-17.-valuing-climate-adaptation-reducing-heatwave-deaths" class="nav-link" data-scroll-target="#question-17.-valuing-climate-adaptation-reducing-heatwave-deaths">Question 17. Valuing Climate Adaptation: Reducing Heatwave Deaths</a>
  <ul>
  <li><a href="#part-a-2" id="toc-part-a-2" class="nav-link" data-scroll-target="#part-a-2">Part A</a></li>
  <li><a href="#part-b-2" id="toc-part-b-2" class="nav-link" data-scroll-target="#part-b-2">Part B</a></li>
  </ul></li>
  <li><a href="#question-18.-negative-externalities" id="toc-question-18.-negative-externalities" class="nav-link" data-scroll-target="#question-18.-negative-externalities">Question 18. Negative Externalities</a>
  <ul>
  <li><a href="#part-a-3" id="toc-part-a-3" class="nav-link" data-scroll-target="#part-a-3">Part A</a></li>
  <li><a href="#part-b-3" id="toc-part-b-3" class="nav-link" data-scroll-target="#part-b-3">Part B</a></li>
  <li><a href="#part-c-2" id="toc-part-c-2" class="nav-link" data-scroll-target="#part-c-2">Part C</a></li>
  <li><a href="#part-d-2" id="toc-part-d-2" class="nav-link" data-scroll-target="#part-d-2">Part D</a></li>
  </ul></li>
  <li><a href="#question-19.-market-for-pollution" id="toc-question-19.-market-for-pollution" class="nav-link" data-scroll-target="#question-19.-market-for-pollution">Question 19. Market for Pollution</a>
  <ul>
  <li><a href="#part-a-4" id="toc-part-a-4" class="nav-link" data-scroll-target="#part-a-4">Part A</a></li>
  <li><a href="#part-b-4" id="toc-part-b-4" class="nav-link" data-scroll-target="#part-b-4">Part B</a></li>
  </ul></li>
  <li><a href="#question-20.-flood-game-disaster-relief-and-nfip-style-problems" id="toc-question-20.-flood-game-disaster-relief-and-nfip-style-problems" class="nav-link" data-scroll-target="#question-20.-flood-game-disaster-relief-and-nfip-style-problems">Question 20. Flood Game, Disaster Relief, and NFIP-Style Problems</a>
  <ul>
  <li><a href="#part-a.-key-concept-1" id="toc-part-a.-key-concept-1" class="nav-link" data-scroll-target="#part-a.-key-concept-1">Part A. Key Concept 1</a></li>
  <li><a href="#part-b.-key-concept-2" id="toc-part-b.-key-concept-2" class="nav-link" data-scroll-target="#part-b.-key-concept-2">Part B. Key Concept 2</a></li>
  <li><a href="#part-c.-key-concept-3" id="toc-part-c.-key-concept-3" class="nav-link" data-scroll-target="#part-c.-key-concept-3">Part C. Key Concept 3</a></li>
  <li><a href="#part-d.-homeowners-best-responses" id="toc-part-d.-homeowners-best-responses" class="nav-link" data-scroll-target="#part-d.-homeowners-best-responses">Part D. Homeowner’s Best Responses</a></li>
  <li><a href="#part-e.-governments-best-responses" id="toc-part-e.-governments-best-responses" class="nav-link" data-scroll-target="#part-e.-governments-best-responses">Part E. Government’s Best Responses</a></li>
  <li><a href="#part-f.-nash-equilibria" id="toc-part-f.-nash-equilibria" class="nav-link" data-scroll-target="#part-f.-nash-equilibria">Part F. Nash Equilibria</a></li>
  <li><a href="#part-g.-moral-hazard-in-the-flood-game" id="toc-part-g.-moral-hazard-in-the-flood-game" class="nav-link" data-scroll-target="#part-g.-moral-hazard-in-the-flood-game">Part G. Moral Hazard in the Flood Game</a></li>
  <li><a href="#part-h.-linking-the-game-to-nfip-and-disaster-relief-policy" id="toc-part-h.-linking-the-game-to-nfip-and-disaster-relief-policy" class="nav-link" data-scroll-target="#part-h.-linking-the-game-to-nfip-and-disaster-relief-policy">Part H. Linking the Game to NFIP and Disaster Relief Policy</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ECON 340 - Final Exam</h1>
<p class="subtitle lead">SUNY Geneseo, Fall 2025</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 10, 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="section-1.-multiple-choice" class="level1">
<h1>Section 1. Multiple Choice</h1>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<p>According to the Coase Theorem, if transaction costs are negligible, the final efficient outcome of a negotiation between a polluter and a victim is determined by:</p>
<ol type="a">
<li>Which party has greater bargaining power.</li>
<li>The initial assignment of property rights.</li>
<li>The relative benefits and costs of the polluting activity.</li>
<li>The amount of the Pigovian tax imposed.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong> <strong>c</strong></p>
<p>With negligible transaction costs, bargaining leads to the <em>efficient</em> outcome regardless of who holds the initial property right; efficiency is determined by whether the activity’s benefits exceed its harms (i.e., net gains).</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>Farmer Alpha can drain a wetland to grow crops, earning $5,000 in additional profit. However, this would cause $8,000 in flood damage to downstream neighbor Beta. Suppose Beta holds the legal right to keep the wetland undrained (Alpha must obtain Beta’s consent to drain). Under the Coase theorem (no transaction costs), what is the efficient outcome and why?</p>
<ol type="a">
<li>The wetland is drained because Alpha’s profit ($5,000) exceeds what he earns if he does not drain.</li>
<li>The wetland is preserved because Alpha’s maximum willingness to pay for the right to drain ($5,000) is less than Beta’s minimum willingness to accept compensation to allow drainage ($8,000).</li>
<li>The wetland is drained because Beta’s damages ($8,000) are greater than Alpha’s profit ($5,000).</li>
<li>The wetland is preserved because Beta must pay Alpha at least $5,000 to prevent drainage.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong> <strong>b</strong><br>
Efficiency requires comparing total benefits and damages. Draining yields +$5,000 but causes −$8,000, so net is −$3,000. Even if Alpha tries to buy permission, he won’t pay more than $5,000, while Beta won’t accept less than $8,000—so no trade occurs and the wetland stays undrained.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<p>Which empirical method is most commonly used by economists to estimate the Value of Statistical Life?</p>
<ol type="a">
<li>Surveying individuals about their willingness to pay for healthcare.</li>
<li>Aggregating the medical costs associated with treating fatal diseases.</li>
<li>Calculating the lifetime earnings of an average worker.</li>
<li>Wage-risk analysis comparing extra pay for riskier jobs.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong> <strong>d</strong><br>
The standard approach is <em>hedonic wage</em> (or wage–risk) estimation: infer WTP for small mortality-risk reductions from observed wage premiums in riskier occupations.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-4" class="level2">
<h2 class="anchored" data-anchor-id="question-4">Question 4</h2>
<p>In environmental cost–benefit analysis, we discount future costs and benefits mainly because:</p>
<ol type="a">
<li>Inflation makes future dollars worth less in nominal terms</li>
<li>Future environmental damages are always smaller than present damages</li>
<li>Discounting makes it easier to justify delaying climate policy</li>
<li>People and societies typically prefer consumption now and have alternative investment opportunities</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong> <strong>d</strong><br>
Discounting reflects (i) time preference (benefits now are valued more than later) and (ii) opportunity cost of capital (resources invested today can grow over time).</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-5" class="level2">
<h2 class="anchored" data-anchor-id="question-5">Question 5</h2>
<p>Which feature is specific to a Climate Club rather than a Carbon Border Adjustment Mechanism (CBAM)?</p>
<ol type="a">
<li>Sector-specific tariffs on a few EITE (energy-intensive, trade-exposed) industries only.</li>
<li>An economy-wide external tariff imposed on all imports from non-members.</li>
<li>Focus exclusively on carbon pricing, never subsidies.</li>
<li>No impact on free-riding incentives.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong> <strong>b</strong><br>
A <em>Climate Club</em> is a membership-based arrangement where members coordinate policy (often carbon pricing) and impose a penalty (e.g., tariff) on <strong>non-members</strong> to discourage free-riding. A CBAM is typically tied to embodied carbon in specific imported products/sectors rather than an economy-wide “club penalty.”</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-6" class="level2">
<h2 class="anchored" data-anchor-id="question-6">Question 6</h2>
<p>Consider an EU-style CBAM that imposes a tariff equal to the difference between the domestic and foreign carbon price times the carbon content of imports. What is the main intended effect?</p>
<ol type="a">
<li>Equalize the effective carbon cost on domestic and foreign producers and reduce carbon leakage.</li>
<li>Lower domestic carbon prices to support industry.</li>
<li>Subsidize foreign producers who adopt green technologies.</li>
<li>Eliminate all trade in EITE sectors.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong> <strong>a</strong><br>
The purpose is to level the playing field by charging imports an equivalent carbon price (based on carbon content), which aims to reduce relocation of emissions-intensive production (“leakage”) and protect the integrity of domestic climate policy.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-7" class="level2">
<h2 class="anchored" data-anchor-id="question-7">Question 7</h2>
<p>What is the primary role of the Intergovernmental Panel on Climate Change (IPCC)?</p>
<ol type="a">
<li>To conduct original climate research and fund decarbonization projects.</li>
<li>To provide policymakers with regular scientific assessments on climate change by synthesizing peer-reviewed studies.</li>
<li>To negotiate and enforce international climate agreements like the Paris Agreement.</li>
<li>To develop Integrated Assessment Models (IAMs) like GIVE for calculating the Social Cost of Carbon.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong> <strong>b</strong><br>
The IPCC does not primarily conduct original research or enforce agreements; it assesses and synthesizes existing scientific literature to inform decision-making.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-8" class="level2">
<h2 class="anchored" data-anchor-id="question-8">Question 8</h2>
<p>Which of the following best captures a regressivity concern with energy or carbon taxes?</p>
<ol type="a">
<li>High-income households pay more in total dollars.</li>
<li>Low-income households spend a larger share of their income on energy, so a uniform per-unit tax can take a larger fraction of their budget.</li>
<li>Energy taxes cannot be recycled back to households.</li>
<li>Regressivity is not a concern if the tax is Pigovian.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong> <strong>b</strong><br>
That’s the definition of a <em>regressive</em> burden: the tax consumes a larger percentage of income for poorer households even if richer households pay more dollars total.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-9" class="level2">
<h2 class="anchored" data-anchor-id="question-9">Question 9</h2>
<p>Which two behavioral biases best explain why homeowners, despite living in a high-risk flood zone, might delay purchasing flood insurance because they gradually forget past flood events and assume a serious flood is unlikely to happen to them?</p>
<ol type="a">
<li>Simplification</li>
<li>Social Herding</li>
<li>Optimism</li>
<li>Amnesia</li>
<li>Myopia</li>
<li>Inertia</li>
<li>Moral Hazard</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong> <strong>c (Optimism)</strong> and <strong>d (Amnesia)</strong></p>
<ul>
<li><strong>Amnesia:</strong> people “forget” or underweight past floods as time passes.<br>
</li>
<li><strong>Optimism bias:</strong> “It won’t happen to me,” leading to underestimation of personal risk and delaying insurance purchase.</li>
</ul>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="section-2.-filling-in-the-blanks" class="level1">
<h1>Section 2. Filling-in-the-Blanks</h1>
<section id="question-10" class="level2">
<h2 class="anchored" data-anchor-id="question-10">Question 10</h2>
<p>Fill in the blank for each <strong>source of market failure</strong> commonly used in environmental economics:</p>
<ul>
<li>_________________________ — private production or consumption decisions impose unpriced environmental costs or benefits on others (e.g., air pollution, ecosystem damage)<br>
</li>
<li>_________________________ — non-excludability leads to free-riding in provision of environmental quality (e.g., climate mitigation, biodiversity conservation)<br>
</li>
<li>_________________________ — rival but hard-to-exclude environmental resources are overused (e.g., fisheries, groundwater, open-access forests)<br>
</li>
<li>_________________________ — when consumers or policymakers lack accurate or complete facts about environmental risks or product attributes, leading to distorted choices (e.g., hidden pollution)</li>
<li>_________________________ — split incentive between the decision-maker and the payer lead to underinvestment in efficiency (e.g., landlord–tenant problems)<br>
</li>
<li>_________________________ — bounded rationality, willpower, and social norms affect decisions drive systematic mistakes in environmental decisions (e.g., ignoring flood risk)<br>
</li>
<li>_________________________ — market power (monopoly or collusive oligopoly) distorts price and quantity, potentially worsening or sometimes reducing environmental harm</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>Externalities</strong> — private production or consumption decisions impose unpriced environmental costs or benefits on others (e.g., air pollution, ecosystem damage).<br>
<strong>Explanation:</strong> When spillover harms/benefits aren’t priced, markets overproduce “bads” (pollution) and underprovide “goods” (abatement).</p></li>
<li><p><strong>Public goods</strong> — non-excludability leads to free-riding in provision of environmental quality (e.g., climate mitigation, biodiversity conservation).<br>
<strong>Explanation:</strong> If people can’t be excluded from benefits, many prefer to free-ride, so provision is below the social optimum.</p></li>
<li><p><strong>Common-pool resources</strong> — rival but hard-to-exclude environmental resources are overused (e.g., fisheries, groundwater, open-access forests).<br>
<strong>Explanation:</strong> Because the resource is rival and exclusion is difficult, individuals ignore congestion/depletion costs imposed on others.</p></li>
<li><p><strong>Information problem</strong> — when consumers or policymakers lack accurate or complete facts about environmental risks or product attributes, leading to distorted choices (e.g., hidden pollution).<br>
<strong>Explanation:</strong> Hidden attributes/risks can cause adverse selection, moral hazard, or simply misinformed decisions.</p></li>
<li><p><strong>Principal–agent problem</strong> — split incentive between the decision-maker and the payer leads to underinvestment in efficiency (e.g., landlord–tenant problems).<br>
<strong>Explanation:</strong> The party who would pay for upgrades may not capture the savings, so efficient investments don’t happen.</p></li>
<li><p><strong>Behavioral anomalies</strong> — bounded rationality, willpower, and social norms affect decisions and drive systematic mistakes (e.g., ignoring flood risk).<br>
<strong>Explanation:</strong> Biases like myopia, inertia, and optimism cause predictable underinvestment in protection/mitigation relative to what people would choose with full attention and foresight.</p></li>
<li><p><strong>Lack of competition</strong> — market power (monopoly or collusive oligopoly) distorts price and quantity, potentially worsening or sometimes reducing environmental harm.<br>
<strong>Explanation:</strong> Firms with market power restrict output and raise prices; this changes production (and pollution) away from the competitive outcome.</p></li>
</ul>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-11" class="level2">
<h2 class="anchored" data-anchor-id="question-11">Question 11</h2>
<p>To estimate the _________________________, an Integrated Assessment Models (IAMs) combines four core building blocks: (i) future _________________________ and emissions pathways, (ii) a _________________________ model linking emissions to temperature and sea level, (iii) a _________________________ function that maps climate variables into economic damages, and (iv) _________________________ to convert future damages into present value.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>To estimate the <strong>Social Cost of Carbon (SCC)</strong>, an Integrated Assessment Model (IAM) combines four core building blocks:<br>
(i) future <strong>socioeconomic (population and GDP) pathways</strong> and emissions pathways,<br>
(ii) a <strong>climate</strong> model linking emissions to temperature and sea level,<br>
(iii) a <strong>damage</strong> function that maps climate variables into economic damages, and<br>
(iv) <strong>discounting</strong> to convert future damages into present value.</p>
<p><strong>Explanation:</strong> IAMs connect “economy → emissions → climate → damages → present value,” producing a dollar-per-ton CO₂ estimate.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-12" class="level2">
<h2 class="anchored" data-anchor-id="question-12">Question 12</h2>
<p>Under present bias, individuals value the present disproportionately more than the future, applying a _________________________ discount rate to near-term outcomes and a _________________________ discount rate to distant outcomes.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Under present bias, individuals value the present disproportionately more than the future, applying a <strong>high</strong> discount rate to near-term outcomes and a <strong>low</strong> discount rate to distant outcomes.</p>
<p><strong>Explanation:</strong> This is the intuition behind hyperbolic (or quasi-hyperbolic) discounting: people are especially impatient about the near term, but more patient about tradeoffs further out.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-13" class="level2">
<h2 class="anchored" data-anchor-id="question-13">Question 13</h2>
<p>Carbon pricing is based on economic theory, which argues it aligns private costs with social costs, incentivizing emissions reduction. However, practical challenges include setting the appropriate price, avoiding the shift of emissions to countries with less stringent policies, often referred to as _________________________, and ensuring public support.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Carbon pricing is based on economic theory, which argues it aligns private costs with social costs, incentivizing emissions reduction. However, practical challenges include setting the appropriate price, avoiding the shift of emissions to countries with less stringent policies, often referred to as <strong>carbon leakage</strong>, and ensuring public support.</p>
<p><strong>Explanation:</strong> If production relocates to unregulated jurisdictions, global emissions may fall less than expected (or even rise), undermining the policy.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="question-14" class="level2">
<h2 class="anchored" data-anchor-id="question-14">Question 14</h2>
<p>FEMA relies mainly on _________________________ purchase and<br>
_________________________ disclosure, which are often<br>
_________________________ when myopia, optimism, and inertia are present.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>FEMA relies mainly on <strong>voluntary</strong> purchase and <strong>information/risk</strong> disclosure, which are often <strong>insufficient</strong> when myopia, optimism, and inertia are present.</p>
<p><strong>Explanation:</strong> When households procrastinate, underestimate risk, or stick with defaults, voluntary take-up and information alone may not generate adequate protection or insurance coverage.</p>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="section-3.-short-answers" class="level1">
<h1>Section 3. Short Answers</h1>
<section id="question-15-risk-uncertainty-and-the-precautionary-principle" class="level2">
<h2 class="anchored" data-anchor-id="question-15-risk-uncertainty-and-the-precautionary-principle">Question 15 — Risk, Uncertainty, and the Precautionary Principle</h2>
<section id="part-a" class="level3">
<h3 class="anchored" data-anchor-id="part-a">Part A</h3>
<p>What is risk in economics?</p>
<p><em>Write approximately 1–2 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In economics, <strong>risk</strong> refers to situations where the possible outcomes are known and probabilities can be assigned to those outcomes. Individuals can form expectations and evaluate choices using expected values.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-b" class="level3">
<h3 class="anchored" data-anchor-id="part-b">Part B</h3>
<p>Describe how a risk-averse person compares a certain outcome to a risky gamble with the same expected value.</p>
<p><em>Write approximately 3–5 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong><br>
A risk-averse person prefers a certain outcome to a risky gamble with the same expected value. This is because potential losses are weighted more heavily than equally sized gains, so variability in outcomes is viewed negatively. Even when the average payoff is the same, the uncertainty itself reduces the attractiveness of the gamble.</p>
<p>As a result, the person is willing to accept a sufficiently lower guaranteed payoff to avoid risk.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-c" class="level3">
<h3 class="anchored" data-anchor-id="part-c">Part C</h3>
<p>Distinguish between “risk” and “uncertainty” in Economics.</p>
<p><em>Write approximately 2–3 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Under <strong>risk</strong>, the set of possible outcomes and their probabilities are known or can be estimated.</p>
<p>Under <strong>uncertainty</strong>, probabilities are unknown or not well defined, making it impossible to calculate expected values in a standard way.</p>
<!-- Uncertainty is often associated with novel or poorly understood phenomena, such as long-run climate impacts. -->
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-d" class="level3">
<h3 class="anchored" data-anchor-id="part-d">Part D</h3>
<p>What is the precautionary principle?</p>
<p><em>Write approximately 1–2 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <strong>precautionary principle</strong> holds that when potential impacts are large, irreversible, and deeply uncertain, policymakers should take preventive action rather than relying solely on expected value calculations. It emphasizes acting cautiously in the face of potential large damages, particularly when scientific evidence is incomplete.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-e" class="level3">
<h3 class="anchored" data-anchor-id="part-e">Part E</h3>
<p>Explain how the precautionary principle can be seen as a response to both risk aversion and uncertainty.</p>
<ul>
<li>In your answer, connect:
<ul>
<li>Risk aversion, and<br>
</li>
<li>Deep uncertainty about low-probability, high-damage events</li>
</ul></li>
</ul>
<p><em>Write approximately 3–5 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The precautionary principle reflects <strong>risk aversion</strong> by prioritizing the avoidance of potentially catastrophic losses, even if those losses are unlikely. It also responds to <strong>deep uncertainty</strong>, where probabilities of extreme climate or environmental damages are unknown or poorly understood. In such cases, expected value calculations may understate true risks. Acting precautiously can therefore be seen as a rational response to both preferences over risk and limits to scientific knowledge.</p>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="question-16-social-discount-rate-sdr-and-social-cost-of-carbon-scc" class="level2">
<h2 class="anchored" data-anchor-id="question-16-social-discount-rate-sdr-and-social-cost-of-carbon-scc">Question 16 — Social Discount Rate (SDR) and Social Cost of Carbon (SCC)</h2>
<section id="part-a-1" class="level3">
<h3 class="anchored" data-anchor-id="part-a-1">Part A</h3>
<p>The Ramsey formula is given by:<br>
<span class="math display">\[
SDR = \rho + \eta g,
\]</span> where <span class="math inline">\(\rho\)</span> is the <strong>pure rate of time preference</strong>, <span class="math inline">\(\eta\)</span> is the <strong>elasticity of marginal utility of consumption</strong>, and <span class="math inline">\(g\)</span> is the <strong>growth rate of consumption per capita</strong>.</p>
<ul>
<li>In words, explain:
<ul>
<li>the economic intuition behind each term <span class="math inline">\(\rho\)</span>, <span class="math inline">\(\eta\)</span>, and <span class="math inline">\(g\)</span>;<br>
</li>
<li>what <span class="math inline">\(\eta\)</span> and <span class="math inline">\(g\)</span> <strong>together</strong> determine in the context of discounting; and<br>
</li>
<li>how changes in <span class="math inline">\(g\)</span> are likely to affect the <strong>social cost of carbon (SCC)</strong>, holding other parameters fixed.</li>
</ul></li>
</ul>
<p><em>Write approximately 5–7 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong></p>
<ul>
<li><p>The pure rate of time preference <span class="math inline">\(\rho\)</span> reflects how much society values present utility over future utility simply because it occurs sooner.</p></li>
<li><p>The elasticity of marginal utility <span class="math inline">\(\eta\)</span> captures how rapidly marginal utility declines as consumption rises, reflecting aversion to inequality across generations.</p>
<ul>
<li>Because extra consumption benefits the poor <strong>more than</strong> the rich, a higher <span class="math inline">\(\eta\)</span> means society places <strong>greater weight on poorer or earlier generations</strong> when choosing how to allocate resources over time.</li>
</ul></li>
<li><p>The growth rate of consumption per capita <span class="math inline">\(g\)</span> measures how fast future generations are expected to be richer.</p></li>
<li><p>Together, <span class="math inline">\(\eta\)</span> and <span class="math inline">\(g\)</span> determine how growth in consumption translates into growth in social welfare, and thus how strongly future climate damages are discounted when they fall on wealthier generations.</p></li>
<li><p>A higher <span class="math inline">\(g\)</span> increases the SDR, which lowers the present value of future climate damages and therefore reduces the SCC, holding other parameters fixed.</p></li>
</ul>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-b-1" class="level3">
<h3 class="anchored" data-anchor-id="part-b-1">Part B</h3>
<ul>
<li>What is the opportunity cost of capital?<br>
</li>
<li>Explain the economic intuition for why the opportunity cost of capital can be used as a benchmark for choosing the SDR in climate-policy cost–benefit analysis.</li>
</ul>
<p><em>Write approximately 3–5 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong><br>
The <strong>opportunity cost of capital (OCC)</strong> is the <strong>return forgone</strong> when spending $1 today on a project, instead of <strong>investing that same $1 in the best available alternative</strong> (for example, in private capital markets or government bonds).</p>
<p>In cost–benefit analysis, using resources for climate mitigation means forgoing other productive investments. The OCC therefore reflects the social rate of return that society sacrifices by investing in climate policy. Using it as a benchmark for the SDR ensures that climate investments are evaluated consistently with other uses of capital.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-c-1" class="level3">
<h3 class="anchored" data-anchor-id="part-c-1">Part C</h3>
<p>Should the Social Cost of Carbon (SCC) reflect global climate damages or only domestic ones? What are the ethical and policy implications of each approach?</p>
<p><em>Write approximately 3–5 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong><br>
Using a global SCC accounts for climate damages suffered by all countries and reflects the fact that climate change is a global externality. This approach is ethically grounded in valuing all human welfare equally, regardless of nationality, and supports stronger climate action.</p>
<p>A domestic SCC counts only damages within national borders, which may align more closely with national policy mandates but understates total harms.</p>
<p>The choice has important policy implications, as a global SCC generally justifies more ambitious mitigation efforts.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-d-1" class="level3">
<h3 class="anchored" data-anchor-id="part-d-1">Part D</h3>
<p>Some economists argue for declining social discount rates over very long horizons. Explain how uncertainty about future economic growth might justify using a declining SDR, and how this would affect the SCC and long-run climate policy decisions.</p>
<p><em>Write approximately 3–5 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer:</strong><br>
When future economic growth is uncertain, different growth paths imply different future market interest rates and levels of consumption.</p>
<p>In expected present-value calculations with <strong>risk aversion</strong>, states of the world with <strong>low growth and low interest rates</strong> receive relatively <em>more weight</em> over long horizons. In these states, future consumption is lower, and future damages should be discounted less. Therefore, the discount rate should decline with the time horizon. This provides a justification for using a <strong>declining SDR</strong> rather than a constant one.</p>
<p>A lower long-run SDR increases the present value of far-future climate damages, raising the SCC and strengthening the case for earlier and more ambitious climate mitigation and adaptation policies.</p>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
</section>
<section id="section-5.-analytical-modeling" class="level1">
<h1>Section 5. Analytical Modeling</h1>
<section id="question-17.-valuing-climate-adaptation-reducing-heatwave-deaths" class="level2">
<h2 class="anchored" data-anchor-id="question-17.-valuing-climate-adaptation-reducing-heatwave-deaths">Question 17. Valuing Climate Adaptation: Reducing Heatwave Deaths</h2>
<p>A <strong>climate adaptation measure</strong>—for example, adding more public cooling centers and strengthening heat-warning systems—is projected to cut the <strong>annual risk of death from extreme heat</strong> from <strong>5 per 100,000 people</strong> to <strong>2 per 100,000 people</strong> in a city with a population of <strong>3 million</strong>.</p>
<section id="part-a-2" class="level3">
<h3 class="anchored" data-anchor-id="part-a-2">Part A</h3>
<p>By how many <strong>statistical lives per year</strong> does this policy reduce expected heat-related deaths?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Change in individual annual risk:</p>
<p><span class="math inline">\(\Delta \text{risk} = \dfrac{5}{100000} - \dfrac{2}{100000} = \dfrac{3}{100000} = 3 \times 10^{-5}\)</span></p>
<p>Population size: <span class="math inline">\(3{,}000{,}000\)</span></p>
<p>Expected number of statistical lives saved per year:</p>
<p><span class="math inline">\(\text{Lives saved} = 3{,}000{,}000 \times 3 \times 10^{-5} = 90\)</span></p>
<p><strong>Answer:</strong> The policy saves <strong>90 statistical lives per year</strong>.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-b-2" class="level3">
<h3 class="anchored" data-anchor-id="part-b-2">Part B</h3>
<p>Assume the <strong>Value of a Statistical Life (VSL)</strong> is <strong>$8 million</strong>. Based <strong>only on the reduction in mortality risk</strong>, what is the <strong>highest annual cost</strong> that would still make this policy worthwhile for society?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>VSL: <span class="math inline">\(\$8{,}000{,}000\)</span> per statistical life</p>
<p>Annual benefit from reduced mortality:</p>
<p><span class="math inline">\(\text{Annual benefit} = 90 \times 8{,}000{,}000 = 720{,}000{,}000\)</span></p>
<p>So the benefit is <span class="math inline">\(\$720\)</span> million per year.</p>
<p><strong>Answer:</strong> The maximum annual cost that can be justified based on mortality-risk reduction alone is <strong><span class="math inline">\(\$720\)</span> million per year</strong>.</p>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="question-18.-negative-externalities" class="level2">
<h2 class="anchored" data-anchor-id="question-18.-negative-externalities">Question 18. Negative Externalities</h2>
<p>Suppose a factory produces goods under the private marginal cost function <span class="math display">\[
MC(Q) = Q + 1
\]</span></p>
<p>where <span class="math inline">\(Q\)</span> is the quantity of output. Currently, the factory is causing environmental pollution in the surrounding area, and the external marginal cost (<span class="math inline">\(EMC\)</span>) of this pollution is defined as <span class="math display">\[
EMC(Q) = 4.
\]</span> Let <span class="math inline">\(P\)</span> be the price of the goods produced in the factory. The quantity demanded for the goods is <span class="math display">\[
Q_{D}(P) = 20 − 2P.
\]</span></p>
<section id="part-a-3" class="level3">
<h3 class="anchored" data-anchor-id="part-a-3">Part A</h3>
<p>Solve for the market equilibrium level of price and quantity.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output-display">
<p><img src="econ-340-exam-3_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>Rewrite demand in inverse form: <span class="math display">\[
Q = 20 - 2P \;\Rightarrow\; P = 10 - \tfrac{1}{2}Q.
\]</span> In a competitive market, price equals private marginal cost: <span class="math display">\[
P = MC(Q) = Q + 1.
\]</span> Setting demand equal to private marginal cost: <span class="math display">\[
10 - \tfrac{1}{2}Q = Q + 1 \;\Rightarrow\; 9 = \tfrac{3}{2}Q \;\Rightarrow\; Q_M = 6.
\]</span> Substituting back: <span class="math display">\[
P_M = Q_M + 1 = 7.
\]</span></p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-b-3" class="level3">
<h3 class="anchored" data-anchor-id="part-b-3">Part B</h3>
<p>Solve for the socially optimal level of price and quantity.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Social marginal cost is the sum of private and external marginal costs: <span class="math display">\[
SMC(Q) = MC(Q) + EMC(Q) = (Q + 1) + 4 = Q + 5.
\]</span> Set inverse demand equal to social marginal cost: <span class="math display">\[
10 - \tfrac{1}{2}Q = Q + 5 \;\Rightarrow\; 5 = \tfrac{3}{2}Q \;\Rightarrow\; Q^* = \tfrac{10}{3}.
\]</span> The corresponding price is: <span class="math display">\[
P^* = 10 - \tfrac{1}{2}\cdot\tfrac{10}{3} = \tfrac{25}{3}.
\]</span></p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-c-2" class="level3">
<h3 class="anchored" data-anchor-id="part-c-2">Part C</h3>
<p>What is the size of the deadweight loss caused by the producer’s activity?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The deadweight loss is the triangle between demand and social marginal cost from <span class="math inline">\(Q^*\)</span> to <span class="math inline">\(Q_M\)</span>.<br>
The base is: <span class="math display">\[
Q_M - Q^* = 6 - \tfrac{10}{3} = \tfrac{8}{3}.
\]</span> The height is the marginal external cost: <span class="math display">\[
EMC = 4.
\]</span> Thus, deadweight loss is: <span class="math display">\[
DWL = \tfrac{1}{2} \times \tfrac{8}{3} \times 4 = \tfrac{16}{3}.
\]</span></p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-d-2" class="level3">
<h3 class="anchored" data-anchor-id="part-d-2">Part D</h3>
<p>Let <span class="math inline">\(T\)</span> denote the environmental tax levied on each unit of the goods produced. If the regulatory authority decides to internalize social damage by an environmental tax, solve the optimal value for <span class="math inline">\(T\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The optimal Pigouvian tax equals the marginal external cost at the efficient level of output. Since <span class="math display">\[
EMC(Q) = 4
\]</span> is constant, the optimal per-unit tax is: <span class="math display">\[
T^* = 4.
\]</span> This tax shifts the private marginal cost to coincide with social marginal cost and induces the socially optimal quantity <span class="math inline">\(Q^*=\tfrac{10}{3}\)</span>.</p>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="question-19.-market-for-pollution" class="level2">
<h2 class="anchored" data-anchor-id="question-19.-market-for-pollution">Question 19. Market for Pollution</h2>
<p>Two firms—Firm 1 and Firm 2—can control emissions at the following marginal cost of emission reduction for each firm: <span class="math display">\[\begin{align*}
MC_{1} &amp;= \text{\$}200\times q_{1},\\
MC_{2} &amp;= \text{\$}100\times q_{2},
\end{align*}\]</span> where <span class="math inline">\(q_{1}\)</span> and <span class="math inline">\(q_{2}\)</span> are, respectively, the amount of emissions reduced by the first and second firms.</p>
<section id="part-a-4" class="level3">
<h3 class="anchored" data-anchor-id="part-a-4">Part A</h3>
<ul>
<li>Compute the cost-effective allocation of emission control responsibility (<span class="math inline">\(q_{1}\)</span> and <span class="math inline">\(q_{2}\)</span>) if a total reduction of 21 units of emissions is necessary.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Cost-effectiveness requires equalizing marginal abatement costs across firms: <span class="math display">\[
MC_1 = MC_2 \quad\Rightarrow\quad 200q_1 = 100q_2 \quad\Rightarrow\quad q_2 = 2q_1.
\]</span> The total reduction requirement is: <span class="math display">\[
q_1 + q_2 = 21.
\]</span> Substitute <span class="math inline">\(q_2=2q_1\)</span>: <span class="math display">\[
q_1 + 2q_1 = 21 \Rightarrow 3q_1=21 \Rightarrow q_1=7,
\quad q_2=14.
\]</span> So the cost-effective allocation is: <span class="math display">\[
(q_1,q_2) = (7,14).
\]</span></p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-b-4" class="level3">
<h3 class="anchored" data-anchor-id="part-b-4">Part B</h3>
<p>Assume that with no pollution control at all, each firm would be emitting 20 units of emissions. Suppose 10 tradable pollution permits were initially given to Firm 2 and 9 were initially given to Firm 1 for free.</p>
<ul>
<li>How many permits would each firm end up with after trading?</li>
<li>What would be the marginal cost of emission reduction at the equilibrium?</li>
<li>What would the net permit expenditure be for each firm after trading?</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Step 1: Use total emissions and permit cap.</strong><br>
Without control, each firm emits 20, so baseline total emissions are <span class="math inline">\(40\)</span>.<br>
A total reduction of <span class="math inline">\(21\)</span> implies total allowed emissions are: <span class="math display">\[
40 - 21 = 19.
\]</span> So the total number of permits must be <span class="math inline">\(19\)</span> (consistent with <span class="math inline">\(10+9=19\)</span>).</p>
<p><strong>Step 2: Connect permits to abatement.</strong><br>
If a firm ends up with <span class="math inline">\(E_i\)</span> permits, it emits <span class="math inline">\(E_i\)</span>, so its abatement is: <span class="math display">\[
q_i = 20 - E_i.
\]</span></p>
<p><strong>Step 3: Use the cost-effective abatement from Part A.</strong><br>
From Part A: <span class="math display">\[
q_1=7,\quad q_2=14.
\]</span> Thus equilibrium emissions (and permits held) are: <span class="math display">\[
E_1 = 20-7=13,\qquad E_2 = 20-14=6.
\]</span> So after trading:</p>
<ul>
<li>Firm 1 ends up with <strong>13 permits</strong></li>
<li>Firm 2 ends up with <strong>6 permits</strong></li>
</ul>
<p><strong>Step 4: Marginal cost at the trading equilibrium.</strong><br>
At the efficient allocation, MACs are equal: <span class="math display">\[
MC_1 = 200q_1 = 200(7)=1400,\qquad MC_2 = 100q_2 = 100(14)=1400.
\]</span> So the equilibrium permit price (and common marginal abatement cost) is: <span class="math display">\[
p = 1400.
\]</span></p>
<p><strong>Step 5: Net permit expenditure for each firm.</strong><br>
Initial endowments: Firm 1 has 9 permits, Firm 2 has 10 permits.<br>
Final holdings: Firm 1 has 13, Firm 2 has 6.</p>
<ul>
<li>Firm 1 buys <span class="math inline">\(13-9=4\)</span> permits, so net expenditure: <span class="math display">\[
+4\times 1400 = +5600.
\]</span></li>
<li>Firm 2 sells <span class="math inline">\(10-6=4\)</span> permits, so net expenditure (negative = revenue): <span class="math display">\[
-4\times 1400 = -5600.
\]</span></li>
</ul>
<p><strong>Final results:</strong></p>
<ul>
<li>Permits after trading: Firm 1 = <strong>13</strong>, Firm 2 = <strong>6</strong><br>
</li>
<li>Equilibrium MAC (permit price): <strong>$1400 per unit</strong><br>
</li>
<li>Net permit expenditure: Firm 1 pays <strong>$5600</strong>, Firm 2 receives <strong>$5600</strong></li>
</ul>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="question-20.-flood-game-disaster-relief-and-nfip-style-problems" class="level2">
<h2 class="anchored" data-anchor-id="question-20.-flood-game-disaster-relief-and-nfip-style-problems">Question 20. Flood Game, Disaster Relief, and NFIP-Style Problems</h2>
<p>Consider a coastal community where homes are exposed to flood risk. A representative homeowner and the federal government interact over <strong>flood insurance</strong> and <strong>post-disaster aid</strong>. Think of this as a very simple model of the policy tensions behind FEMA’s <strong>National Flood Insurance Program (NFIP)</strong> and repeated federal disaster relief.</p>
<ul>
<li>The home is worth $200,000.<br>
</li>
<li>Each year there is a 5% chance of a major flood that causes $100,000 in damage.<br>
</li>
<li>An <strong>NFIP-style federal flood insurance policy</strong> is available that <strong>fully covers</strong> this $100,000 loss.<br>
</li>
<li>The annual premium for full coverage is <strong>$3,000</strong> (a subsidized, below–actuarially-fair premium, like NFIP rates in some areas).<br>
</li>
<li>If the homeowner does <strong>not</strong> buy NFIP coverage and a flood occurs, the government can choose whether to provide an emergency <strong>bailout</strong> that covers <strong>80% of the loss</strong> (i.e., pays $80,000 to the homeowner, leaving $20,000 unrecovered) through <strong>ad hoc disaster assistance</strong> (grants, loans, rebuilding funds, etc.).</li>
</ul>
<p>For simplicity, assume that the homeowner is <strong>risk-neutral</strong> and cares only about expected wealth. The government cares about minimizing its <strong>expected cost</strong>, which includes both direct fiscal outlays and the <strong>political cost</strong> of not helping uninsured households. Government’s political cost is large enough that, when the homeowner is uninsured, the government’s total expected cost is the same whether it provides a bailout or not.</p>
<p>We model this as a <strong>2-player flood game</strong>:</p>
<ul>
<li>Player 1 (Homeowner) chooses:
<ul>
<li><strong>I</strong>: Buy full NFIP flood insurance.<br>
</li>
<li><strong>NI</strong>: Do not buy NFIP insurance.</li>
</ul></li>
<li>Player 2 (Government) chooses:
<ul>
<li><strong>B</strong>: Provide a bailout (post-disaster aid) to uninsured households after a flood.<br>
</li>
<li><strong>NB</strong>: Commit to <strong>no</strong> bailout.</li>
</ul></li>
</ul>
<p>You are given the following <strong>computed expected values</strong> for each strategy profile:</p>
<ul>
<li>Homeowner’s expected wealth <span class="math inline">\(W\)</span> as a function of the two players’ strategies:
<ul>
<li><span class="math inline">\(E[W(I,B)] = 197,000\)</span></li>
<li><span class="math inline">\(E[W(I,NB)] = 197,000\)</span></li>
<li><span class="math inline">\(E[W(NI,B)] = 199,000\)</span></li>
<li><span class="math inline">\(E[W(NI,NB)] = 195,000\)</span></li>
</ul></li>
<li>Government’s expected cost (including political cost):
<ul>
<li><span class="math inline">\(C_G(I,B) = 0\)</span></li>
<li><span class="math inline">\(C_G(I,NB) = 0\)</span></li>
<li><span class="math inline">\(C_G(NI,B) = 4,000\)</span></li>
<li><span class="math inline">\(C_G(NI,NB) = 4,000\)</span></li>
</ul></li>
</ul>
<p>Assume the government’s payoff is the negative of its expected cost: <span class="math display">\[
-C_G.
\]</span></p>
<p>Using the values above, a <strong>payoff matrix</strong> for this game (in <strong>thousands of dollars</strong>) is:</p>
<ul>
<li><strong>Rows</strong> = Homeowner strategies <span class="math inline">\((I, NI)\)</span><br>
</li>
<li><strong>Columns</strong> = Government strategies <span class="math inline">\((B, NB)\)</span><br>
</li>
<li><strong>Each cell</strong> reports payoffs as <span class="math inline">\((\text{Homeowner’s expected wealth},\ \text{Government’s payoff})\)</span>.</li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th></th>
<th><strong>Government</strong></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td><strong>B</strong></td>
<td><strong>NB</strong></td>
</tr>
<tr class="even">
<td><strong>Homeowner</strong></td>
<td><strong>I</strong></td>
<td>(197, 0)</td>
<td>(197, 0)</td>
</tr>
<tr class="odd">
<td></td>
<td><strong>NI</strong></td>
<td>(199, -4)</td>
<td>(195, -4)</td>
</tr>
</tbody>
</table>
<section id="part-a.-key-concept-1" class="level3">
<h3 class="anchored" data-anchor-id="part-a.-key-concept-1">Part A. Key Concept 1</h3>
<p>What are the <strong>three basic goals</strong> of the National Flood Insurance Program (NFIP)?</p>
<p><em>Write in one sentence for each basic goal.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Provide <strong>flood insurance</strong> where <strong>private market</strong> is thin.</li>
<li>Lower the need for <strong>emergency federal disaster assistance</strong>.</li>
<li>Encourage <strong>safer building &amp; land-use practices</strong> in flood-prone areas.</li>
</ol>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-b.-key-concept-2" class="level3">
<h3 class="anchored" data-anchor-id="part-b.-key-concept-2">Part B. Key Concept 2</h3>
<p>Provide a definition of moral hazard.</p>
<p><em>Write approximately 1–2 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Moral hazard</strong> occurs when having insurance causes people to <strong>change their behavior</strong>, taking <strong>more risk</strong> because they do <strong>not bear the full cost</strong> of bad outcomes.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-c.-key-concept-3" class="level3">
<h3 class="anchored" data-anchor-id="part-c.-key-concept-3">Part C. Key Concept 3</h3>
<p>Explain why <strong>NFIP costs and debt are rising</strong> in relation to each of the following:</p>
<ol type="1">
<li><strong>Climate hazard</strong><br>
</li>
<li><strong>Exposure</strong><br>
</li>
<li><strong>Vulnerability</strong></li>
</ol>
<p><em>Write approximately 3–5 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>Climate hazard:</strong> Flood risk has increased due to stronger storms, heavier rainfall, and sea-level rise, leading to more frequent and severe flood losses covered by NFIP.<br>
</li>
<li><strong>Exposure:</strong> Continued development and repeated rebuilding in flood-prone areas increase the number and value of insured properties, raising total claims paid by the program.<br>
</li>
<li><strong>Vulnerability:</strong> Aging or insufficient flood protection infrastructure, rising construction and repair costs, and the <strong>legacy underpricing of premiums</strong> increase per-claim losses and prevent NFIP revenues from keeping pace with growing risk.</li>
</ul>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-d.-homeowners-best-responses" class="level3">
<h3 class="anchored" data-anchor-id="part-d.-homeowners-best-responses">Part D. Homeowner’s Best Responses</h3>
<p>Using the payoff matrix:</p>
<ul>
<li>When Government chooses <span class="math inline">\(B\)</span>, the Homeowner’s best response is ________________.<br>
</li>
<li>When Government chooses <span class="math inline">\(NB\)</span>, the Homeowner’s best response is ________________.</li>
</ul>
<p>Briefly justify each answer using the payoffs.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p>When Government chooses <span class="math inline">\(B\)</span>, the Homeowner’s best response is <strong>NI</strong>.<br>
If the government chooses <span class="math inline">\(B\)</span>, the homeowner compares <span class="math inline">\(E[W(I,B)]=197\)</span> to <span class="math inline">\(E[W(NI,B)]=199\)</span>. Since <span class="math inline">\(199&gt;197\)</span>, the homeowner prefers <strong>not</strong> to buy insurance.</p></li>
<li><p>When Government chooses <span class="math inline">\(NB\)</span>, the Homeowner’s best response is <strong>I</strong>.<br>
If the government chooses <span class="math inline">\(NB\)</span>, the homeowner compares <span class="math inline">\(E[W(I,NB)]=197\)</span> to <span class="math inline">\(E[W(NI,NB)]=195\)</span>. Since <span class="math inline">\(197&gt;195\)</span>, the homeowner prefers to <strong>buy</strong> insurance.</p></li>
</ul>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-e.-governments-best-responses" class="level3">
<h3 class="anchored" data-anchor-id="part-e.-governments-best-responses">Part E. Government’s Best Responses</h3>
<p>Using the payoff matrix:</p>
<ul>
<li>When the Homeowner chooses <span class="math inline">\(I\)</span>, Government’s best response is ________________.<br>
</li>
<li>When the Homeowner chooses <span class="math inline">\(NI\)</span>, Government’s best response is ________________.</li>
</ul>
<p>Briefly justify each answer using the payoffs.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p>When the Homeowner chooses <span class="math inline">\(I\)</span>, the Government’s best response is <strong>either <span class="math inline">\(B\)</span> or <span class="math inline">\(NB\)</span></strong> (it is indifferent).<br>
The government payoff is <span class="math inline">\(0\)</span> under both <span class="math inline">\((I,B)\)</span> and <span class="math inline">\((I,NB)\)</span>, so it has no strict preference.</p></li>
<li><p>When the Homeowner chooses <span class="math inline">\(NI\)</span>, the Government’s best response is <strong>either <span class="math inline">\(B\)</span> or <span class="math inline">\(NB\)</span></strong> (it is indifferent).<br>
The government payoff is <span class="math inline">\(-4\)</span> under both <span class="math inline">\((NI,B)\)</span> and <span class="math inline">\((NI,NB)\)</span>, so it has no strict preference.</p></li>
</ul>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-f.-nash-equilibria" class="level3">
<h3 class="anchored" data-anchor-id="part-f.-nash-equilibria">Part F. Nash Equilibria</h3>
<p>Find all <strong>Nash equilibria</strong> for this game.</p>
<ul>
<li><p>For each equilibrium, explain why <strong>neither player</strong> has an incentive to deviate, given the other player’s strategy.</p></li>
<li><p>Which equilibrium is <strong>more socially desirable</strong> in this model? Briefly explain why.</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Nash equilibria:</strong></p>
<ol type="1">
<li><p><strong><span class="math inline">\((NI, B)\)</span></strong><br>
Given <span class="math inline">\(B\)</span>, the homeowner prefers <span class="math inline">\(NI\)</span> (since <span class="math inline">\(199&gt;197\)</span>). Given <span class="math inline">\(NI\)</span>, the government is indifferent between <span class="math inline">\(B\)</span> and <span class="math inline">\(NB\)</span> (both give payoff <span class="math inline">\(-4\)</span>), so it can choose <span class="math inline">\(B\)</span> without wanting to deviate.</p></li>
<li><p><strong><span class="math inline">\((I, NB)\)</span></strong><br>
Given <span class="math inline">\(NB\)</span>, the homeowner prefers <span class="math inline">\(I\)</span> (since <span class="math inline">\(197&gt;195\)</span>). Given <span class="math inline">\(I\)</span>, the government is indifferent between <span class="math inline">\(B\)</span> and <span class="math inline">\(NB\)</span> (both give payoff <span class="math inline">\(0\)</span>), so it can choose <span class="math inline">\(NB\)</span> without wanting to deviate.</p></li>
</ol>
<p><strong>More socially desirable equilibrium (in this model):</strong> <strong><span class="math inline">\((I, NB)\)</span>.</strong><br>
The sum of payoffs (social well-being) at <strong><span class="math inline">\((I, NB)\)</span></strong> is higher than at <strong><span class="math inline">\((NI, B)\)</span></strong>. The equilibrium <strong><span class="math inline">\((I, NB)\)</span></strong> avoids reliance on post-disaster bailouts and results in a lower expected government cost (0 instead of 4), while still providing the homeowner with relatively high expected wealth. This outcome therefore dominates <strong><span class="math inline">\((NI, B)\)</span></strong> from a social efficiency perspective.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-g.-moral-hazard-in-the-flood-game" class="level3">
<h3 class="anchored" data-anchor-id="part-g.-moral-hazard-in-the-flood-game">Part G. Moral Hazard in the Flood Game</h3>
<p>How does the <strong>expectation of a bailout</strong> (post-disaster aid) create a <strong>moral hazard</strong> problem for the Homeowner in <strong>the Flood Game</strong>?</p>
<p>In your answer, connect the logic of the game to the homeowner’s incentives to:</p>
<ul>
<li>Buy or skip <strong>NFIP flood insurance</strong>,</li>
<li>Rely on the possibility of federal disaster aid instead, and</li>
<li>Explain why it is a <strong>moral hazard</strong> problem.</li>
</ul>
<p><em>Write approximately 3-5 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>When the homeowner expects that the government will provide a bailout (<span class="math inline">\(B\)</span>) after a flood, the homeowner’s best response is to skip insurance (<span class="math inline">\(NI\)</span>) because expected wealth is higher with bailout support (199 vs 197). This means the homeowner relies on post-disaster aid rather than paying the insurance premium up front. The bailout expectation effectively insulates the homeowner from the full financial consequence of being uninsured, weakening incentives to purchase coverage.</p>
<p>That strategic response is a moral hazard problem because public aid encourages more uninsured risk-taking than would occur if households bore the full downside.</p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="part-h.-linking-the-game-to-nfip-and-disaster-relief-policy" class="level3">
<h3 class="anchored" data-anchor-id="part-h.-linking-the-game-to-nfip-and-disaster-relief-policy">Part H. Linking the Game to NFIP and Disaster Relief Policy</h3>
<p>Using the flood game as a simplified model of NFIP and federal disaster relief, discuss how the strategic incentives of the <strong>Homeowner</strong> and the <strong>Government</strong> can help explain real-world problems with U.S. flood policy, such as:</p>
<ul>
<li>Low voluntary take-up of NFIP flood insurance,<br>
</li>
<li>Growing fiscal pressure and debt within NFIP, and</li>
<li>Repeated federal disaster relief for uninsured or underinsured households.</li>
</ul>
<p>In your answer, briefly connect the <strong>Nash equilibria</strong> and best responses in this game to observed patterns of <strong>underinsurance</strong> and reliance on <strong>post-disaster aid</strong> in U.S. flood policy.</p>
<p><em>Write approximately 5-7 sentences.</em></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This game illustrates how expected post-disaster aid weakens incentives to purchase NFIP coverage: anticipating bailouts, homeowners optimally choose <span class="math inline">\(NI\)</span>, since expected wealth is higher when the government provides relief. This strategic behavior leads to widespread <strong>underinsurance</strong>, shrinking the insured risk pool and leaving NFIP with too few premium-paying participants. As a result, premium revenue is <strong>insufficient to absorb catastrophic losses</strong>, forcing NFIP to rely on borrowing after major floods and generating persistent fiscal pressure and debt. Although a no-bailout policy would improve long-run incentives, political and humanitarian pressures make it difficult for the government to credibly commit to <span class="math inline">\(NB\)</span> after disasters. The Nash equilibrium <span class="math inline">\((NI,B)\)</span> thus explains both low voluntary take-up and repeated disaster relief, while the socially preferable outcome <span class="math inline">\((I,NB)\)</span> would require <strong>credible commitment</strong> mechanisms such as mandatory insurance, risk-based pricing, or limits on post-disaster aid.</p>
</div>
</div>
</div>
<p><br></p>


</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script>
document.addEventListener('DOMContentLoaded', function () {
  const btn = document.querySelector('.quarto-btn-toggle');
  if (!btn || !window.bootstrap) return;

  btn.addEventListener('click', function (e) {
    ['#quarto-sidebar', '#quarto-sidebar-glass'].forEach(sel => {
      const el = document.querySelector(sel);
      if (el) bootstrap.Collapse.getOrCreateInstance(el).toggle();
    });
  }, { capture: true });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">powered with github, quarto, and rstudio<br>byeong-hak choe, 2025</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<div id="scroll-padding"></div>
<script src="./assets/js/site.js"></script>
<script src="./assets/js/posts.js"></script>



</body></html>